services:
  - type: web
    name: postmanagement-api
    runtime: docker
    repo: https://github.com/platypuss2303/FA25_PE_PRN232
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
