services:
  - type: web
    name: postmanagement-api
    runtime: docker
    repo: https://github.com/HuyNLH/PRN232-PE_TEST
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
